### ISSUE TITLE
Map X-Remote-User received from http-header to specified system unix user

### ISSUE THREAD

**Issue by sdandey** [cwaldbieser/jhub_remote_user_authenticator#16]
I need to map X-Remote-User (received from SSO) to use a different local unix account to login.  how can I achieve it?

**Comment by cwaldbieser** [comment]
Well, the authenticator basically takes whatever is passed in the header and passes that along to the spawner as the user name.  I suppose you could extend the authenticator to provide some kind of mapping, but it might be easier to do the mapping at your Identity provider and/or the authenticating proxy.  E.g. If your authenticating proxy uses LDAP, maybe you could pull out an attribute on the account that maps to the unix user name?  There's not an out-of-the-box solution.

**Comment by sdandey** [comment]
We're using CA SSO solution and we don't have flexibility to change this attribute .  My best option is to extend this functionality and add a mapping functionality to it.

Can you guide me on where to make this modification in the code.  Should I do it on the get() method as shown below?  Please advise
```

 def get(self):
        header_name = self.authenticator.header_name
        remote_user = self.request.headers.get(header_name, "")
        //logic to map remote_user to local_system user should go here..?
        if remote_user == "":
            raise web.HTTPError(401)

        user = self.user_from_username(remote_user)
        self.set_login_cookie(user)
        next_url = self.get_next_url(user)
        self.redirect(next_url)

```

**Comment by cwaldbieser** [comment]
I think you have the correct idea.  As long as your mapping doesn't block you could do something like `newuser = self.usermap.get(olduser)` and check for a `None` user result.  If you need to fetch the mapping from a database or something else that blocks, you might need to make `get()` a coroutine (i.e. `@gen.coroutine`).  My [jupyterhub CAS authenticator](https://github.com/cwaldbieser/jhub_cas_authenticator/blob/master/jhub_cas_authenticator/cas_auth.py) does this because it needs to validate the user service ticket against a remote HTTPS service.

**Comment by sdandey** [comment]
interesting I would use now the usermap and push the solution for testing.  in between, does your CAS authenticator supports SAML?
